output "rds_endpoint" {
  description = "The endpoint of the RDS instance"
  value       = module.rds.db_endpoint
}
output "eks_cluster_name" {
  description = "The name of the EKS cluster"
  value       = module.eks.cluster_name
}
output "eks_cluster_endpoint" {
  description = "The endpoint of the EKS cluster"
  value       = module.eks.cluster_endpoint
}
output "eks_cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
}
output "eks_oidc_provider_arn" {
  description = "The ARN of the OIDC Provider"
  value       = module.eks.oidc_provider_arn
}
output "eks_cluster_oidc_issuer" {
  description = "The OIDC issuer URL for the cluster"
  value       = module.eks.cluster_oidc_issuer
}
output "eks_node_role_name" {
  value = module.eks.node_role_name
}
output "eks_node_profile_name" {
  value = module.eks.node_profile_name
}
output "vpc_id" {
  value = module.vpc.vpc_id
}
output "route53_zone_id" {
  value = module.dns.route53_zone_id
}
output "acm_certificate_arn" {
  value = module.dns.acm_certificate_arn
}
output "how_to_connect_to_eks" {
  description = "Instructions on how to connect to the EKS cluster"
  value       = "To connect to the EKS cluster, run: aws eks --region eu-central-1 update-kubeconfig --name $${module.eks.cluster_name}"
}
output "route53_name_servers" {
  description = "The Name Servers generated by Route 53 to configure in Namecheap"
  value       = module.dns.name_servers
}
output "ecr_backend_url" {
  value = module.ecr.backend_repository_url
}
output "ecr_frontend_url" {
  value = module.ecr.frontend_repository_url
}
output "grafana_password" {
  value     = random_password.grafana_password.result
  sensitive = true
}

output "github_actions_role_arn" {
  value       = module.github_oidc.role_arn
  description = "ARN utworzonej roli dla GitHub Actions"
}
