output "rds_endpoint" {
  description = "The endpoint of the RDS instance"
  value       = module.rds.db_endpoint
}
output "eks_cluster_name" {
  description = "The name of the EKS cluster"
  value       = module.eks.cluster_name
}
output "eks_cluster_endpoint" {
  description = "The endpoint of the EKS cluster"
  value       = module.eks.cluster_endpoint
}
output "how_to_connect_to_eks" {
  description = "Instructions on how to connect to the EKS cluster"
  value       = "To connect to the EKS cluster, run: aws eks --region <region> update-kubeconfig --name ${module.eks.cluster_name}"
}

output "route53_name_servers" {
  description = "The Name Servers generated by Route 53 to configure in Namecheap"
  value       = module.dns.name_servers
}

output "ecr_backend_url" {
  value = module.ecr.backend_repository_url
}

output "ecr_frontend_url" {
  value = module.ecr.frontend_repository_url
}